{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cashsdk",
    "module": "cashsdk-android",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "cashsdk-android-1.4.0.aar",
          "url": "cashsdk-android-1.4.0.aar",
          "size": 658406,
          "sha512": "f1abca91880a14852161f69b52455b1a1eed2273816a1f9ba3ff6d13c92cdab675ec7c6d815a98078f604910b8027257558807033accec5d4514844f80280868",
          "sha256": "d4b73bde0b1c51b7c708d4ee8aaa7512eb81eea11e2a3700af937d73a2fd74ff",
          "sha1": "14da0c989fa7891c0d9e300b0471c6a6c51c45df",
          "md5": "3af39e20521b39abb9ea2f9e2a2a86e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "9.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "cashsdk-android-1.4.0.aar",
          "url": "cashsdk-android-1.4.0.aar",
          "size": 658406,
          "sha512": "f1abca91880a14852161f69b52455b1a1eed2273816a1f9ba3ff6d13c92cdab675ec7c6d815a98078f604910b8027257558807033accec5d4514844f80280868",
          "sha256": "d4b73bde0b1c51b7c708d4ee8aaa7512eb81eea11e2a3700af937d73a2fd74ff",
          "sha1": "14da0c989fa7891c0d9e300b0471c6a6c51c45df",
          "md5": "3af39e20521b39abb9ea2f9e2a2a86e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cashsdk-android-1.4.0-sources.jar",
          "url": "cashsdk-android-1.4.0-sources.jar",
          "size": 108885,
          "sha512": "5b2f5655dd208987bbe9f2adaf4102f6e075004fd607086db0f2829a15835bf366c95d003317f2742429019b150b2cb2385f4ca3cef936fece121cf2e066fad1",
          "sha256": "ba1973d389b838180125995133d448f51d8dd2cb56c0bcc1661347f6858f7a25",
          "sha1": "4783e77941b3b0c2fcb9190ed627bec76f770813",
          "md5": "9d7e070610baf92d3f5bed05c4070c8c"
        }
      ]
    }
  ]
}
