{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cashsdk",
    "module": "cashsdk-android",
    "version": "1.3.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "cashsdk-android-1.3.0-rc.1.aar",
          "url": "cashsdk-android-1.3.0-rc.1.aar",
          "size": 430510,
          "sha512": "c318d2947223c1c2275f6e0605027df80405fe6334f555c9d53ac9536a55810fe078369802e6d810cf440cc4e00da891065d46e57c8c4ab9d36f3bf030429955",
          "sha256": "47ae91801da751085a9049f971cfd755f6ed4648cd427a632ed4719da68da791",
          "sha1": "78be6685e38508ae74285215e441d74da46354c7",
          "md5": "b2d629a22d94af6298b47f7fa24ae466"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "9.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "cashsdk-android-1.3.0-rc.1.aar",
          "url": "cashsdk-android-1.3.0-rc.1.aar",
          "size": 430510,
          "sha512": "c318d2947223c1c2275f6e0605027df80405fe6334f555c9d53ac9536a55810fe078369802e6d810cf440cc4e00da891065d46e57c8c4ab9d36f3bf030429955",
          "sha256": "47ae91801da751085a9049f971cfd755f6ed4648cd427a632ed4719da68da791",
          "sha1": "78be6685e38508ae74285215e441d74da46354c7",
          "md5": "b2d629a22d94af6298b47f7fa24ae466"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cashsdk-android-1.3.0-rc.1-sources.jar",
          "url": "cashsdk-android-1.3.0-rc.1-sources.jar",
          "size": 64197,
          "sha512": "8d6da07731129877b85d4931d8116dbbdfe0b8ef18756deb5f5bcfbcb8b14546dc081cf2f422ebe2bb51f282b64015128b15deddc83f4b679c42454527c761f0",
          "sha256": "1133d057f1f1eef325d696c264463239b11bd935ee650c002350ecbeb732d60c",
          "sha1": "4abc6bb40dd4ed14ff5515a5a566d4162ef2233c",
          "md5": "829ddf70928b4963d20bcc6eb490ecab"
        }
      ]
    }
  ]
}
